<pre class='metadata'>
Title: Auto-Generate Captions for `<video>`
Shortname: auto-generate-captions
Level: None
Status: w3c/UD
Group: WICG
Repository: yashrajbharti/auto-generate-captions-video
URL: https://yashrajbharti.github.io/auto-generate-captions-video
Editor: Yash Raj Bharti, Independent Contributor https://github.com/yashrajbharti, yashrajbharti@example.com
Abstract: Proposal to enhance the `<video>` element with an `auto-generate-caption` attribute to improve accessibility by natively generating captions for video content.
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: auto-generate-captions
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>


Introduction {#intro}
=====================

For now, see the [explainer]([https://yashrajbharti.github.io/auto-generate-captions-video]).

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
